name: Run Python Script on Schedule

on:
  schedule:
    - cron: "*/30 * * * *"   # every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script (CI mode)
        run: python setup_bot_manual.py
        env:
          CI: true
          
      - name: Check Syntax
        run: python -m py_compile setup_bot_manual.py
        
      - name: Run Bot (CI Mode)
        run: python setup_bot_manual.py
        env:
          CI: true

      - name: Commit CSV results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git checkout main
          git pull origin main || echo "No remote changes"
          git add pending_teams.csv
          git commit -m "Update pending_teams.csv" || echo "No changes to commit"
          git push origin main



